# build 1
language: ruby
cache:
  - bundler
  - pip
rvm:
  - 2.3.1
jdk:
  - oraclejdk16
before_script:
  - pip install --user html5validator
script: ./script/cibuild
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  skip_cleanup: true
  provider: script
  script: ./script/deploy
  on:
    branch: master
